"""unique todolist name

Revision ID: 0623774942ed
Revises: 35116325bcba
Create Date: 2023-04-05 10:43:04.636492

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0623774942ed"
down_revision = "35116325bcba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("to_do_lists", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_to_do_lists_name"), ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("to_do_lists", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_to_do_lists_name"), type_="unique")

    # ### end Alembic commands ###
