"""create db

Revision ID: 0bd72cb7828a
Revises:
Create Date: 2023-03-16 14:34:50.877348

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0bd72cb7828a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=True),
        sa.Column("to_time", sa.Time(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_templates")),
    )
    op.create_table(
        "to_do_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_to_do_lists")),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_task", sa.Integer(), nullable=False),
        sa.Column("id_list", sa.Integer(), nullable=False),
        sa.Column("task_done", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["id_list"], ["to_do_lists.id"], name=op.f("fk_tasks_id_list_to_do_lists")),
        sa.ForeignKeyConstraint(["id_task"], ["task_templates.id"], name=op.f("fk_tasks_id_task_task_templates")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("to_do_lists")
    op.drop_table("task_templates")
    # ### end Alembic commands ###
