"""Creation tables TaskTemplates, Statuses, ToDoLists, Tasks

Revision ID: 26a433f4a610
Revises:
Create Date: 2023-03-14 18:38:51.972939

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26a433f4a610"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "to_do_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("owner", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id_status", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_status"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_task", sa.Integer(), nullable=False),
        sa.Column("id_list", sa.Integer(), nullable=False),
        sa.Column("task_done", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_list"],
            ["to_do_lists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_task"],
            ["task_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("task_templates")
    op.drop_table("to_do_lists")
    op.drop_table("statuses")
    # ### end Alembic commands ###
