"""add reminders

Revision ID: 35116325bcba
Revises: 56e7d9995652
Create Date: 2023-03-30 11:34:02.029727

"""
import sqlalchemy as sa
from alembic import op

from webapp.db import db

# revision identifiers, used by Alembic.
revision = "35116325bcba"
down_revision = "56e7d9995652"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    units_time = op.create_table(
        "units_time",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units_time")),
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_task_template", sa.Integer(), nullable=False),
        sa.Column("time_reminder", sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_task_template"], ["task_templates.id"], name=op.f("fk_reminders_id_task_template_task_templates")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    op.create_table(
        "repeatability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_task_template", sa.Integer(), nullable=False),
        sa.Column("day_start", sa.Date(), nullable=True),
        sa.Column("day_end", sa.Date(), nullable=True),
        sa.Column("id_unit_time", sa.Integer(), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_task_template"], ["task_templates.id"], name=op.f("fk_repeatability_id_task_template_task_templates")
        ),
        sa.ForeignKeyConstraint(
            ["id_unit_time"], ["units_time.id"], name=op.f("fk_repeatability_id_unit_time_units_time")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repeatability")),
    )

    new_units_time: list[dict] = [{"name": "День"}, {"name": "Неделя"}, {"name": "Месяц"}, {"name": "Год"}]
    op.bulk_insert(units_time, new_units_time)
    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("repeatability")
    op.drop_table("reminders")
    op.drop_table("units_time")
    # ### end Alembic commands ###
