"""add users

Revision ID: 56e7d9995652
Revises: 0bd72cb7828a
Create Date: 2023-03-21 15:28:33.298873

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56e7d9995652"
down_revision = "0bd72cb7828a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("telegram_user", sa.String(length=50), nullable=True),
        sa.Column("telegram_id", sa.Integer(), nullable=True),
        sa.Column("active_list", sa.Integer(), nullable=True),
        sa.Column("default_reminder_time", sa.Time(), nullable=True),
        sa.Column("time_start_new_day", sa.Time(), nullable=False),
        sa.Column("week_report", sa.Boolean(), nullable=True),
        sa.Column("month_report", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["active_list"], ["to_do_lists.id"], name=op.f("fk_user_active_list_to_do_lists")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    with op.batch_alter_table("task_templates", schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f("fk_task_templates_owner_user"), "user", ["owner"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_templates", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_task_templates_owner_user"), type_="foreignkey")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    # ### end Alembic commands ###
